package com.pe.proydsw.entidades;
// Generated 01-nov-2017 12:41:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Maquinaria generated by hbm2java
 */
public class Maquinaria  implements java.io.Serializable {


     private int intIdMaquinaria;
     private Categoria categoria;
     private String varNombreMaquinaria;
     private char chrEstado;
     private Set tiempomaquinarias = new HashSet(0);
     private Set registros = new HashSet(0);
     private Set paradas = new HashSet(0);

    public Maquinaria() {
    }

	
    public Maquinaria(int intIdMaquinaria, Categoria categoria, String varNombreMaquinaria, char chrEstado) {
        this.intIdMaquinaria = intIdMaquinaria;
        this.categoria = categoria;
        this.varNombreMaquinaria = varNombreMaquinaria;
        this.chrEstado = chrEstado;
    }
    public Maquinaria(int intIdMaquinaria, Categoria categoria, String varNombreMaquinaria, char chrEstado, Set tiempomaquinarias, Set registros, Set paradas) {
       this.intIdMaquinaria = intIdMaquinaria;
       this.categoria = categoria;
       this.varNombreMaquinaria = varNombreMaquinaria;
       this.chrEstado = chrEstado;
       this.tiempomaquinarias = tiempomaquinarias;
       this.registros = registros;
       this.paradas = paradas;
    }
   
    public int getIntIdMaquinaria() {
        return this.intIdMaquinaria;
    }
    
    public void setIntIdMaquinaria(int intIdMaquinaria) {
        this.intIdMaquinaria = intIdMaquinaria;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getVarNombreMaquinaria() {
        return this.varNombreMaquinaria;
    }
    
    public void setVarNombreMaquinaria(String varNombreMaquinaria) {
        this.varNombreMaquinaria = varNombreMaquinaria;
    }
    public char getChrEstado() {
        return this.chrEstado;
    }
    
    public void setChrEstado(char chrEstado) {
        this.chrEstado = chrEstado;
    }
    public Set getTiempomaquinarias() {
        return this.tiempomaquinarias;
    }
    
    public void setTiempomaquinarias(Set tiempomaquinarias) {
        this.tiempomaquinarias = tiempomaquinarias;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }
    public Set getParadas() {
        return this.paradas;
    }
    
    public void setParadas(Set paradas) {
        this.paradas = paradas;
    }




}


