package com.pe.proydsw.entidades;
// Generated 01-nov-2017 12:41:01 by Hibernate Tools 4.3.1



/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private int intIdRegistro;
     private Maquinaria maquinaria;
     private Turno turno;
     private String varFecha;
     private String varHoraInicio;
     private String varHoraFin;
     private Float floatPorcentajeUtil;

    public Registro() {
    }

	
    public Registro(int intIdRegistro, Maquinaria maquinaria, Turno turno, String varFecha, String varHoraInicio) {
        this.intIdRegistro = intIdRegistro;
        this.maquinaria = maquinaria;
        this.turno = turno;
        this.varFecha = varFecha;
        this.varHoraInicio = varHoraInicio;
    }
    public Registro(int intIdRegistro, Maquinaria maquinaria, Turno turno, String varFecha, String varHoraInicio, String varHoraFin, Float floatPorcentajeUtil) {
       this.intIdRegistro = intIdRegistro;
       this.maquinaria = maquinaria;
       this.turno = turno;
       this.varFecha = varFecha;
       this.varHoraInicio = varHoraInicio;
       this.varHoraFin = varHoraFin;
       this.floatPorcentajeUtil = floatPorcentajeUtil;
    }
   
    public int getIntIdRegistro() {
        return this.intIdRegistro;
    }
    
    public void setIntIdRegistro(int intIdRegistro) {
        this.intIdRegistro = intIdRegistro;
    }
    public Maquinaria getMaquinaria() {
        return this.maquinaria;
    }
    
    public void setMaquinaria(Maquinaria maquinaria) {
        this.maquinaria = maquinaria;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getVarFecha() {
        return this.varFecha;
    }
    
    public void setVarFecha(String varFecha) {
        this.varFecha = varFecha;
    }
    public String getVarHoraInicio() {
        return this.varHoraInicio;
    }
    
    public void setVarHoraInicio(String varHoraInicio) {
        this.varHoraInicio = varHoraInicio;
    }
    public String getVarHoraFin() {
        return this.varHoraFin;
    }
    
    public void setVarHoraFin(String varHoraFin) {
        this.varHoraFin = varHoraFin;
    }
    public Float getFloatPorcentajeUtil() {
        return this.floatPorcentajeUtil;
    }
    
    public void setFloatPorcentajeUtil(Float floatPorcentajeUtil) {
        this.floatPorcentajeUtil = floatPorcentajeUtil;
    }




}


