package com.pe.proydsw.entidades;
// Generated 01-nov-2017 11:12:33 by Hibernate Tools 4.3.1



/**
 * Tiempomaquinaria generated by hbm2java
 */
public class Tiempomaquinaria  implements java.io.Serializable {


     private int intIdTiempoMaquinaria;
     private Maquinaria maquinaria;
     private Turno turno;
     private String varFecha;
     private String varTiempoUso;
     private String varTiempoNouso;

    public Tiempomaquinaria() {
    }

    public Tiempomaquinaria(int intIdTiempoMaquinaria, Maquinaria maquinaria, Turno turno, String varFecha, String varTiempoUso, String varTiempoNouso) {
       this.intIdTiempoMaquinaria = intIdTiempoMaquinaria;
       this.maquinaria = maquinaria;
       this.turno = turno;
       this.varFecha = varFecha;
       this.varTiempoUso = varTiempoUso;
       this.varTiempoNouso = varTiempoNouso;
    }
   
    public int getIntIdTiempoMaquinaria() {
        return this.intIdTiempoMaquinaria;
    }
    
    public void setIntIdTiempoMaquinaria(int intIdTiempoMaquinaria) {
        this.intIdTiempoMaquinaria = intIdTiempoMaquinaria;
    }
    public Maquinaria getMaquinaria() {
        return this.maquinaria;
    }
    
    public void setMaquinaria(Maquinaria maquinaria) {
        this.maquinaria = maquinaria;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getVarFecha() {
        return this.varFecha;
    }
    
    public void setVarFecha(String varFecha) {
        this.varFecha = varFecha;
    }
    public String getVarTiempoUso() {
        return this.varTiempoUso;
    }
    
    public void setVarTiempoUso(String varTiempoUso) {
        this.varTiempoUso = varTiempoUso;
    }
    public String getVarTiempoNouso() {
        return this.varTiempoNouso;
    }
    
    public void setVarTiempoNouso(String varTiempoNouso) {
        this.varTiempoNouso = varTiempoNouso;
    }




}


